# -*- coding: utf-8 -*-
"""Product data for the Green Lotus Spices site.

IMPORTANT — the specification figures below are standard Vietnamese export
grades taken from common trade practice. They are NOT Green Lotus lab data.
Every figure must be checked against your own certificates of analysis before
this branch is merged, because a published specification is a commitment to
the buyer.
"""

TODO = " "  # marker only, see build.py::todo()

# Green Lotus's own product photography, still served from the old site's CDN.
# Stock libraries have no accurate cracked or ground black pepper, so these
# stay until the originals are downloaded into img/.
W = "https://static.wixstatic.com/media/"

PRODUCTS = [
    {
        "slug": "black-pepper",
        "name": "Black Pepper",
        "nav": "Black Pepper",
        "title": "Vietnam Black Pepper Supplier | 500-580 g/l, ASTA | Green Lotus",
        "description": "Vietnamese black pepper in FAQ and ASTA grades, whole, cracked or ground to your mesh. Full specifications, container loading and lead times.",
        "lede": "Vietnamese black pepper in bulk — FAQ and ASTA grades from 500 to 580 g/l, whole, cracked or ground to your mesh.",
        "intro": "Black pepper, the king of spices, is Vietnam's largest spice export and the line we ship most of. We supply it whole, cracked or ground, from standard FAQ through to cleaned ASTA and steam-sterilised grades, matched to the specification your market requires.",
        "origin_heading": "Origin and processing",
        "origin": [
            "Our black pepper comes from Vietnam's pepper belt \u2014 {provinces} \u2014 harvested between February and April. We buy through established collection points and take delivery at the farm gate wherever volume allows.",
            "Processing runs through pre-cleaning, destoning, gravity separation and colour sorting, with steam sterilisation and grinding available on request. Every lot is sampled before loading and a certificate of analysis travels with the shipment.",
        ],
        "thumbs": [
            ("https://images.unsplash.com/photo-1649952052743-5e8f37c348c5?q=80&w=1400&auto=format&fit=crop", "Black peppercorns"),
        ],
        "tables": [
            {
                "caption": "Whole black pepper — export grades",
                "headers": ["Grade", "Bulk density", "Moisture", "Light berries", "Foreign matter", "Typical use"],
                "rows": [
                    ["FAQ 500 g/l", "500 g/l min", "13.5% max", "2% max", "1% max", "Grinding and blending"],
                    ["FAQ 550 g/l", "550 g/l min", "13.5% max", "1% max", "0.5% max", "Retail whole pepper"],
                    ["ASTA 570 g/l", "570 g/l min", "12.5% max", "1% max", "0.5% max", "Food manufacturing"],
                    ["ASTA 580 g/l cleaned", "580 g/l min", "12.5% max", "0.5% max", "0.2% max", "Premium retail, EU and US"],
                    ["Steam sterilised", "550–580 g/l", "12% max", "0.5% max", "0.2% max", "Ready-to-eat applications"],
                ],
            },
            {
                "caption": "Ground and cracked black pepper",
                "headers": ["Cut", "Sieve", "Moisture", "Volatile oil", "Packing"],
                "rows": [
                    ["Cracked", "12–14 mesh", "12.5% max", "2% min", "20 / 25 kg"],
                    ["Coarse ground", "28 mesh", "12.5% max", "2% min", "20 / 25 kg"],
                    ["Medium ground", "32 mesh", "12% max", "2% min", "20 / 25 kg"],
                    ["Fine ground", "40 mesh", "12% max", "1.8% min", "20 / 25 kg"],
                    ["Extra fine ground", "60 mesh", "12% max", "1.8% min", "20 / 25 kg"],
                ],
            },
        ],
        "forms_heading": "The forms we ship most",
        "forms_intro": "Most buyers take black pepper in one of three forms. Each is available across the grades in the table above, and every form can be steam sterilised.",
        "forms": [
            ("Whole peppercorns",
             "The bulk of what we ship. Whole berries hold their volatile oil far longer than ground pepper, so most importers buy whole and grind close to use. Available FAQ 500 and 550 g/l, ASTA 570, and cleaned ASTA 580 g/l for retail packing.",
             "Best for: retail whole pepper, grinders, buyers who mill in-market.",
             "%se0f240_83c63757891b46c9b858121e71899732~mv2.png" % W,
             "Cleaned whole black peppercorns, 550 g/l"),
            ("Cracked, 12\u201314 mesh",
             "Berries broken rather than milled, so the flecks stay visible and the aroma survives. The coarsest cut we produce, and the one that reads as pepper on the plate.",
             "Best for: rubs, crusts, table grinders, visible seasoning.",
             "%se0f240_2c7c02c4fe2341cc950fae5bf2455294~mv2.png" % W,
             "Cracked black pepper, 12 to 14 mesh"),
            ("Ground, 28 to 60 mesh",
             "Milled to your sieve specification \u2014 28 mesh coarse, 32 and 40 medium, 60 fine. We grind to order rather than from stock, because ground pepper loses oil in storage.",
             "Best for: seasoning blends, sauces, ready meals, retail shakers.",
             "%se0f240_6b109017d9064aa29cf18d0b79739767~mv2.png" % W,
             "Finely ground black pepper, 60 mesh"),
        ],
        "related": ["white-pepper", "cassia", "dried-red-chilli"],
    },
    {
        "slug": "white-pepper",
        "name": "White Pepper",
        "nav": "White Pepper",
        "title": "Vietnam White Pepper Exporter | Double Washed | Green Lotus",
        "description": "Single and double washed Vietnamese white pepper, 600-630 g/l. Specifications, packaging and export documentation for bulk buyers.",
        "lede": "Single washed, double washed and ASTA cleaned white pepper from Vietnam, 600 to 630 g/l.",
        "intro": "White pepper is produced from the ripe berries of Piper nigrum. The berries are soaked to soften the outer skin, fermented, decorticated and sun-dried, leaving the inner seed and the cleaner, more restrained heat that white pepper is valued for.",
        "origin_heading": "Origin and processing",
        "origin": [
            "Sourced from the same growing regions as our black pepper \u2014 {provinces} \u2014 then decorticated and washed at partner facilities before grading.",
            "Double washed and ASTA cleaned grades go through additional washing, drying and colour sorting to lift whiteness and cut foreign matter. Grinding to your mesh is available on the same line.",
        ],
        "thumbs": [
            ("https://images.unsplash.com/photo-1600728255690-edd070021d02?q=80&w=1400&auto=format&fit=crop", "White peppercorns"),
        ],
        "tables": [
            {
                "caption": "White pepper — export grades",
                "headers": ["Grade", "Bulk density", "Moisture", "Foreign matter", "Colour"],
                "rows": [
                    ["Single washed", "600 g/l min", "13.5% max", "0.5% max", "Cream"],
                    ["Double washed", "630 g/l min", "13% max", "0.2% max", "Bright white"],
                    ["ASTA cleaned", "630 g/l min", "12.5% max", "0.1% max", "Bright white"],
                    ["Ground, 60 mesh", "—", "12% max", "0.1% max", "Bright white"],
                ],
            },
        ],
        "forms_heading": "The forms we ship",
        "forms_intro": "White pepper is sold on how far it has been washed and how finely it is cut. All three forms are available in single washed, double washed and ASTA cleaned grades.",
        "forms": [
            ("Whole",
             "The standard trade form. Decorticated, washed and dried berries at 600 to 630 g/l depending on grade. Whole white pepper holds its aroma in storage far better than ground, so most buyers mill in their own market.",
             "Best for: retail packing, grinders, buyers who mill in-market.",
             "", ""),
            ("Half cracked",
             "Berries broken rather than milled. Coarser than ground, with the pale flecks still visible, and less prone to the flat taste that ground white pepper develops on the shelf.",
             "Best for: light-coloured sauces, rubs, table grinders.",
             "%se0f240_a622300d4deb45e1b54f865df8b29b6d~mv2.png" % W,
             "Half cracked Vietnamese white pepper"),
            ("Ground, 60 mesh",
             "Milled fine and even. We grind to order rather than from stock, because ground white pepper loses volatile oil quickly once milled.",
             "Best for: white sauces, soups, processed meat, retail shakers.",
             "%se0f240_34e9fdeff5f6400b9da5cbfe69da53e9~mv2.png" % W,
             "Vietnamese white pepper ground to 60 mesh"),
        ],
        "related": ["black-pepper", "cassia", "star-anise"],
    },
    {
        "slug": "cassia",
        "name": "Cassia",
        "nav": "Cassia",
        "title": "Vietnam Cassia Cinnamon Supplier | Split, Tube, Broken",
        "description": "Vietnamese cassia in split, tube, broken and ground form. Volatile oil specifications, provinces of origin and container quantities.",
        "lede": "Vietnamese cassia — Cinnamomum cassia in split, tube, broken and ground form, with volatile oil from 2.5%.",
        "intro": "Cassia is the bark of the Cinnamomum cassia tree, stripped, trimmed and dried into the cuts the trade works with. Vietnamese cassia carries a higher volatile oil content than most origins, which is why grinders and oleoresin buyers ask for it by name.",
        "origin_heading": "Origin and processing",
        "origin": [
            "Our cassia comes from the traditional growing districts of {cassia_provinces}, where the bark is harvested, scraped and sun-dried before grading by cut and length.",
            "We supply split, tube, broken, chips and ground cassia, cut to the length your line runs. Coumarin and volatile oil results are available per lot for buyers shipping into the EU.",
        ],
        "thumbs": [
            ("https://images.unsplash.com/photo-1553499944-e4297a0af1bd?q=80&w=1400&auto=format&fit=crop", "Cassia cinnamon sticks"),
        ],
        "tables": [
            {
                "caption": "Cassia — cuts and specifications",
                "headers": ["Cut", "Form", "Moisture", "Volatile oil"],
                "rows": [
                    ["Split", "Flat pieces", "13.5% max", "2.5% min"],
                    ["Tube / quill", "Rolled bark", "13.5% max", "3% min"],
                    ["Broken / chips", "Irregular", "13.5% max", "2.5% min"],
                    ["Ground", "Powder", "12% max", "2% min"],
                ],
            },
        ],
        "forms_heading": "The cuts we ship",
        "forms_intro": "Cassia is traded by the shape the bark is cut into. The cut drives the price more than the grade does, so it is worth telling us which one your line runs.",
        "forms": [
            ("Split and tube",
             "Bark dried flat as splits, or rolled into tubes and quills. The premium cuts, cut to the length your packing line or your retail pack needs.",
             "Best for: retail cinnamon sticks, mulling spice, visible garnish.",
             "%se0f240_b5a6d00a905544689753653e13aee308~mv2.jpg" % W,
             "Vietnamese cassia cut into sticks"),
            ("Broken and chips",
             "Irregular pieces from trimming and from bark too short to roll. Identical material to the splits at a lower price, which is why grinders and oleoresin extractors buy it by preference.",
             "Best for: grinding, oleoresin extraction, brewing and distilling.",
             "%se0f240_0ebacd12c71149d0ab7e28a1a8a9d99e~mv2.jpg" % W,
             "Cleaned broken cassia and chips"),
            ("Ground",
             "Milled to your specification, with volatile oil from 2%% and coumarin results available per lot for buyers shipping into the EU.",
             "Best for: bakery, seasoning blends, retail ground cinnamon.",
             "%se0f240_a2e89e4397e849faa42a44afb843b30d~mv2.png" % W,
             "Cassia bark and ground cassia"),
        ],
        "related": ["star-anise", "black-pepper", "dried-red-chilli"],
    },
    {
        "slug": "star-anise",
        "name": "Star Anise",
        "nav": "Star Anise",
        "title": "Vietnam Star Anise Exporter | Autumn & Spring Crop",
        "description": "Whole and broken Vietnamese star anise, autumn and spring crop, EU and organic grades. Full specifications and bulk packaging.",
        "lede": "Whole and broken star anise from northern Vietnam — autumn and spring crop, EU and organic grades.",
        "intro": "Star anise is the dried fruit of Illicium verum, native to northeast Vietnam and southern China. The autumn crop carries the fuller flower and the higher oil content, and is what most buyers specify for whole-pod retail and for oil extraction.",
        "origin_heading": "Origin and processing",
        "origin": [
            "Our star anise comes from {anise_provinces} in the northeast, harvested green and sun-dried. Autumn crop runs from August to October, spring crop from March to April.",
            "We supply EU grade and organic certified lots, cleaned, sorted and graded by pod integrity. Broken and ground are available for extraction buyers.",
        ],
        "thumbs": [
            ("https://images.unsplash.com/photo-1638779024471-abb09390e23a?q=80&w=1400&auto=format&fit=crop", "Whole star anise"),
        ],
        "tables": [
            {
                "caption": "Star anise — grades",
                "headers": ["Grade", "Description", "Moisture", "Broken", "Volatile oil"],
                "rows": [
                    ["Autumn crop, whole", "Full flowers, 8–10 petals", "13% max", "5% max", "8% min"],
                    ["Spring crop, whole", "Full flowers", "13% max", "5% max", "7% min"],
                    ["Broken", "Petals and fragments", "13% max", "—", "7% min"],
                    ["Organic certified", "Full flowers", "13% max", "5% max", "8% min"],
                ],
            },
        ],
        "forms_heading": "The forms we ship",
        "forms_intro": "Star anise is bought on pod integrity and on volatile oil. Whole pods carry the premium; broken material goes to extraction at a lower price.",
        "forms": [
            ("Whole pods",
             "Full flowers with eight to ten petals, cleaned and sorted. Autumn crop carries the fuller pod and the higher oil, typically 8%% against 7%% for spring crop. Organic certified lots available.",
             "Best for: retail whole spice, stocks and broths, mulling, visible garnish.",
             "%se0f240_659d66416daf45c1bf7df4956daa6dd7~mv2.png" % W,
             "Whole Vietnamese star anise pods"),
            ("Broken",
             "Loose petals and fragments from sorting. The same crop as the whole pods, priced lower because the shape is gone, which makes it the sensible buy if the pod is going to be milled or extracted anyway.",
             "Best for: oil and oleoresin extraction, brewing, infusions.",
             "", ""),
            ("Ground",
             "Milled to your mesh from whole or broken pods. We grind to order, because the anethole that gives star anise its character is volatile and goes off in storage once the pod is opened up.",
             "Best for: five-spice powder, seasoning blends, bakery, ready meals.",
             "", ""),
        ],
        "related": ["cassia", "black-pepper", "dried-red-chilli"],
    },
    {
        "slug": "cashews",
        "name": "Cashews",
        "nav": "Cashews",
        "title": "Vietnam Cashew Kernel Supplier | W180 to W450 | Green Lotus",
        "description": "Vietnamese cashew kernels in W180, W240, W320 and W450 plus scorched and pieces. Vacuum packed, AFI grades, export ready.",
        "lede": "Vietnamese cashew kernels — W180 through W450, scorched grades and pieces, vacuum packed to AFI standards.",
        "intro": "Vietnam is the world's largest cashew processor, and the grading language is the AFI standard every buyer works to. We supply the full white wholes range, scorched grades and pieces, vacuum packed for export.",
        "origin_heading": "Origin and processing",
        "origin": [
            "Raw nuts are sourced from {cashew_provinces}, the heart of Vietnamese cashew growing, then shelled, peeled, graded and packed at partner facilities.",
            "Kernels are vacuum packed and cartoned to your required tin or pouch size. Metal detection and moisture checks run on every lot before sealing.",
        ],
        "thumbs": [
            ("https://images.unsplash.com/photo-1726771517475-e7acdd34cd8a?q=80&w=1400&auto=format&fit=crop", "Cashew kernels"),
        ],
        "tables": [
            {
                "caption": "Cashew kernels — AFI grades",
                "headers": ["Grade", "Description", "Count per lb", "Moisture", "Broken max"],
                "rows": [
                    ["W180", "White wholes, largest", "170–180", "5% max", "5%"],
                    ["W240", "White wholes", "220–240", "5% max", "5%"],
                    ["W320", "White wholes, most traded", "300–320", "5% max", "5%"],
                    ["W450", "White wholes, small", "400–450", "5% max", "5%"],
                    ["SW / SSW", "Scorched wholes", "Per size", "5% max", "5%"],
                    ["LWP / SWP", "Large and small white pieces", "—", "5% max", "—"],
                ],
            },
        ],
        "forms_heading": "The grades we ship",
        "forms_intro": "Cashews are graded to the AFI standard the whole trade works to. Wholes command the premium; scorched grades and pieces cost less for identical kernel.",
        "forms": [
            ("White wholes, W180 to W450",
             "Ivory kernels, unbroken, graded by count per pound. W320 is the most traded size worldwide; W180 is the largest and scarcest. Vacuum packed and cartoned.",
             "Best for: retail packing, gifting, roasted and salted snacks.",
             "%se0f240_8312b6dbe49b4f6899672858fb76985f~mv2.jpeg" % W,
             "White whole cashew kernels"),
            ("Scorched wholes, SW and SSW",
             "Whole kernels that picked up colour during roasting. The flavour and the size are unchanged, only the shade, so they cost meaningfully less than white wholes of the same count.",
             "Best for: confectionery, bakery, nut butters, anything roasted or coated.",
             "", ""),
            ("Pieces, LWP and SWP",
             "Large and small white pieces from kernels broken in shelling. Same kernel, no premium for shape.",
             "Best for: baking, cereal and snack bars, cashew butter, curry pastes.",
             "", ""),
        ],
        "related": ["desiccated-coconut", "black-pepper", "star-anise"],
    },
    {
        "slug": "dried-red-chilli",
        "name": "Dried Red Chilli",
        "nav": "Dried Red Chilli",
        "title": "Dried Red Chilli Supplier Vietnam | Whole, Flakes, Powder",
        "description": "Vietnamese dried red chilli whole, stemless, crushed and ground. ASTA colour value and Scoville rating supplied per lot.",
        "lede": "Vietnamese dried red chilli — whole with stem, stemless, crushed and ground, with ASTA colour and Scoville per lot.",
        "intro": "Dried red chilli is graded on two numbers before anything else: colour value and heat. We supply whole pods, stemless, crushed flakes and powder, and issue both figures per lot so buyers can match the blend they already run.",
        "origin_heading": "Origin and processing",
        "origin": [
            "Chilli is sourced from {chilli_provinces}, harvested ripe and either sun-dried or machine-dried to hold colour.",
            "Cleaning, destemming, crushing and grinding run in-line, with metal detection before packing. Steam sterilisation is available for ready-to-eat applications.",
        ],
        "thumbs": [
            ("https://images.unsplash.com/photo-1602237514002-c2d8ae2da393?q=80&w=1400&auto=format&fit=crop", "Dried red chillies"),
        ],
        "tables": [
            {
                "caption": "Dried red chilli — forms and specifications",
                "headers": ["Form", "Cut", "Moisture", "Colour and heat"],
                "rows": [
                    ["Whole, with stem", "Dried pods", "12% max", "Per lot analysis"],
                    ["Whole, stemless", "Dried pods", "12% max", "Per lot analysis"],
                    ["Crushed / flakes", "3–5 mm", "10% max", "Per lot analysis"],
                    ["Powder", "Ground to your mesh", "10% max", "Per lot analysis"],
                ],
            },
        ],
        "forms_heading": "The forms we ship",
        "forms_intro": "Chilli is bought on colour value and heat before anything else, and both are supplied with the lot analysis. The form then depends on where it goes in your process.",
        "forms": [
            ("Whole pods, with stem or stemless",
             "Sun-dried or machine-dried to hold colour. Stemless costs a little more to produce but saves you the sorting, and it is what most food manufacturers specify.",
             "Best for: retail whole chilli, pastes and sauces, infusing oils.",
             "%se0f240_0fdde82605014494aea1339632f34fef~mv2.jpeg" % W,
             "Dried red chilli pods"),
            ("Crushed flakes, 3 to 5 mm",
             "Pods broken with the seed left in, so the heat stays high and the flakes stay visible.",
             "Best for: pizza and pasta shakers, kimchi, seasoning blends.",
             "", ""),
            ("Powder",
             "Ground to your mesh, with or without seed depending on the heat you want. Steam sterilisation available for ready-to-eat applications.",
             "Best for: sauces, ready meals, curry and spice blends, retail packing.",
             "", ""),
        ],
        "related": ["black-pepper", "cassia", "star-anise"],
    },
    {
        "slug": "desiccated-coconut",
        "name": "Desiccated Coconut",
        "nav": "Desiccated Coconut",
        "title": "Desiccated Coconut Vietnam | Fine, Medium, Coarse",
        "description": "Vietnamese desiccated coconut in fine, medium, coarse and low fat grades. Full micro specifications and food-grade packaging.",
        "lede": "Vietnamese desiccated coconut — fine, medium, coarse and low fat, with full microbiological specifications.",
        "intro": "Desiccated coconut is made from mature coconut flesh, grated and dried to a shelf-stable ingredient. Food manufacturers buy on cut, fat content and microbiology, so all three are set out below.",
        "origin_heading": "Origin and processing",
        "origin": [
            "Coconuts are sourced from {coconut_provinces} in the Mekong Delta, dehusked, pared, grated and hot-air dried within hours of opening.",
            "We supply sulphured and unsulphured grades. Each lot ships with a microbiological report covering total plate count, yeast and mould, E. coli and salmonella.",
        ],
        "thumbs": [
            ("https://images.unsplash.com/photo-1582362731298-b3f9789a17ce?q=80&w=1400&auto=format&fit=crop", "Desiccated coconut"),
        ],
        "tables": [
            {
                "caption": "Desiccated coconut — grades",
                "headers": ["Grade", "Cut", "Moisture", "Fat", "Free fatty acid"],
                "rows": [
                    ["Fine", "1.0–1.6 mm", "3% max", "60–65%", "0.3% max"],
                    ["Medium", "1.6–2.5 mm", "3% max", "60–65%", "0.3% max"],
                    ["Coarse / chips", "2.5 mm and above", "3% max", "60–65%", "0.3% max"],
                    ["Low fat", "Fine or medium", "3% max", "On request", "0.3% max"],
                ],
            },
            {
                "caption": "Microbiological limits",
                "headers": ["Test", "Limit"],
                "rows": [
                    ["Total plate count", "5,000 cfu/g max"],
                    ["Yeast and mould", "50 cfu/g max"],
                    ["E. coli", "Absent"],
                    ["Salmonella", "Absent in 25 g"],
                ],
            },
        ],
        "forms_heading": "The cuts we ship",
        "forms_intro": "Desiccated coconut is sold on cut size, fat content and microbiology. All three cuts come from the same mature nuts, dried within hours of opening.",
        "forms": [
            ("Fine, 1.0 to 1.6 mm",
             "The most traded cut. Disperses evenly through a batter or a dough and takes up moisture without clumping.",
             "Best for: bakery, confectionery, biscuit fillings, retail packing.",
             "%se0f240_396fb75ca7ce4aaa94569c4effda8667~mv2.jpg" % W,
             "Fine desiccated coconut"),
            ("Medium, 1.6 to 2.5 mm",
             "A visible shred that still mixes cleanly. The usual choice when the coconut should be seen as well as tasted.",
             "Best for: macaroons, coated confectionery, cereal and muesli.",
             "", ""),
            ("Coarse and chips, 2.5 mm and above",
             "Long shreds and flat chips, for topping rather than mixing.",
             "Best for: toppings, granola, snack packs, decoration.",
             "", ""),
        ],
        "related": ["cashews", "black-pepper", "star-anise"],
    },
]

PRODUCTS_BY_SLUG = {p["slug"]: p for p in PRODUCTS}

# Cards shown on our-spices.html, reusing the existing photography.
RANGE_CARDS = [
    ("black-pepper", "https://images.unsplash.com/photo-1649952052743-5e8f37c348c5?q=80&w=1400&auto=format&fit=crop",
     "Black peppercorns",
     "FAQ 500 and 550 g/l through to cleaned ASTA 580 g/l and steam sterilised. Whole, cracked or ground from 12 to 60 mesh."),
    ("white-pepper", "https://images.unsplash.com/photo-1600728255690-edd070021d02?q=80&w=1400&auto=format&fit=crop",
     "White peppercorns",
     "Single washed, double washed and ASTA cleaned, 600 to 630 g/l. Whole, cracked and ground."),
    ("cassia", "https://images.unsplash.com/photo-1553499944-e4297a0af1bd?q=80&w=1400&auto=format&fit=crop",
     "Cassia cinnamon sticks",
     "Split, tube, broken, chips and ground, from the northern highlands. Volatile oil from 2.5%, coumarin results per lot."),
    ("star-anise", "https://images.unsplash.com/photo-1638779024471-abb09390e23a?q=80&w=1400&auto=format&fit=crop",
     "Whole star anise",
     "Autumn and spring crop, whole and broken, EU and organic grades. Volatile oil from 7%."),
    ("cashews", "https://images.unsplash.com/photo-1726771517475-e7acdd34cd8a?q=80&w=1400&auto=format&fit=crop",
     "Cashew kernels",
     "W180, W240, W320 and W450 white wholes, scorched grades and pieces. Vacuum packed to AFI standards."),
    ("desiccated-coconut", "https://images.unsplash.com/photo-1582362731298-b3f9789a17ce?q=80&w=1400&auto=format&fit=crop",
     "Desiccated coconut",
     "Fine, medium, coarse and low fat. Sulphured and unsulphured, with full microbiological reports."),
    ("dried-red-chilli", "https://images.unsplash.com/photo-1602237514002-c2d8ae2da393?q=80&w=1400&auto=format&fit=crop",
     "Dried red chillies",
     "Whole with stem, stemless, crushed flakes and powder. ASTA colour value and Scoville rating supplied per lot."),
]
